deploy file configure and added deployment test controller to check

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -40,14 +40,49 @@ jobs:
       - name: Check for Test Projects
         run: dotnet test AutoHub.slnx --configuration Release --no-build
       
-      - name: Test SSH Connection
+      - name: Deploy to EC2
         uses: appleboy/ssh-action@v1.2.2
+        env:
+          BRANCH_NAME: ${{ github.ref_name }}
         with:
           host: ${{ secrets.EC2_HOST }}
           username: ${{ secrets.EC2_USERNAME }}
           key: ${{ secrets.EC2_SSH_KEY }}
+          envs: BRANCH_NAME
           script: |
-            echo "Connected successfully!"
-            whoami
-            pwd
-            hostname
+            set -e
+
+            echo "Deploying branch: $BRANCH_NAME"
+
+            cd ~/projects/AutoHub-API
+
+            git fetch origin
+
+            git checkout $BRANCH_NAME
+
+            git pull origin $BRANCH_NAME
+
+            docker compose -f docker-compose.prod.yml up -d --build
+
+            docker image prune -f
+
+            echo "Deployment completed successfully!"
+
+            echo "Waiting 30 seconds for the application to start..."
+            
+            sleep 30
+
+            echo "Starting health checks..."
+
+            for i in {1..10}; do
+              if curl -fs https://${{ secrets.DOMAIN }}/health > /dev/null; then
+                echo "Application is healthy!"
+                exit 0
+              fi
+
+              echo "Health check failed (Attempt $i/10). Retrying in 30 seconds..."
+              sleep 30
+            done
+
+            echo "Health check failed after 10 attempts."
+            exit 1
